default:
  NAME: PRODUCTS
  PORT: 8088
  HOST: localhost
  CORS_ORIGINS: [ "*" ]

  DEBUG: false
  RELOADED: false
  LIFESPAN: on

  POSTGRES:
    echo: false
    echo_pool: false
    driver: postgresql+asyncpg
    port: 5432
    user: postgres
    host: database
    password: postgres
    database: postgres
    pool_pre_ping: true
    pool_recycle: 3000