version: "3.8"

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basket_database
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/basket_database
    ports:
      - 8000:8000
    command: sh -c "poetry install &&
      poetry run uvicorn app.application:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:


