"""auto

Revision ID: 88328801a14b
Revises: 
Create Date: 2024-12-15 18:13:18.518409+03:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88328801a14b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("name", sa.String(), nullable=False, comment="Наименоваие продукта"),
        sa.Column("price", sa.Integer(), nullable=False, comment="стоимость продукта"),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Идентификатор",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Продукт",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("product")
    # ### end Alembic commands ###
