"""auto

Revision ID: 92f734071f35
Revises: 88328801a14b
Create Date: 2024-12-15 19:26:32.564129+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '92f734071f35'
down_revision: Union[str, None] = '88328801a14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('count', sa.Integer(), nullable=False, comment='Количество продуктов'))
    op.alter_column('product', 'name',
                    existing_type=sa.VARCHAR(),
                    comment='Наименование продукта',
                    existing_comment='Наименоваие продукта',
                    existing_nullable=False)
    op.alter_column('product', 'price',
                    existing_type=sa.INTEGER(),
                    comment='Стоимость продукта',
                    existing_comment='стоимость продукта',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
                    existing_type=sa.INTEGER(),
                    comment='стоимость продукта',
                    existing_comment='Стоимость продукта',
                    existing_nullable=False)
    op.alter_column('product', 'name',
                    existing_type=sa.VARCHAR(),
                    comment='Наименоваие продукта',
                    existing_comment='Наименование продукта',
                    existing_nullable=False)
    op.drop_column('product', 'count')
    # ### end Alembic commands ###
